title: WHAI
email: info@thisiswh.ai
description: >-
  Exploring AI's uncharted realms and fostering innovation. Unlocking creativity through generative AI, while embracing transparency and curiosity.
baseurl: ""
url: "thisiswh.ai"
twitter_username: thisiswhai
github_username: thisiswhai

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
